export const REQUEST = 'LOGIN_REQUEST';

export const LOGIN_SEND_SUCCESS = 'LOGIN_SEND_SUCCESS';
export const LOGOUT_SEND_SUCCESS = 'LOGOUT_SEND_SUCCESS';
export const LOGIN_SEND_SUCCESS_CONFIRM = 'LOGIN_SEND_SUCCESS_CONFIRM';

export const PROFILE_READ_DATA = 'PROFILE_READ_DATA';

export const CHANGED = 'CHANGED';

export const WITHDRAW_SEND_SUCCESS = 'WITHDRAW_SEND_SUCCESS';

export const CHARGE_GET_SUCCESS = 'CHARGE_GET_SUCCESS';
export const CHARGE_POST_SUCCESS = 'CHARGE_POST_SUCCESS';

export const GET_STREAM_SUCCESS = 'GET_STREAM_SUCCESS';

export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS';


export const FAILURE = 'LOGIN_FAILURE';